SELECT A.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
-- 2022년 1월의 데이터만 조회하기 위해 형식 맞추기
WHERE TRUNC(S.SALES_DATE, 'MM') = DATE '2022-01-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC