-- 코드를 입력하세요
SELECT *
FROM (
    SELECT DISTINCT C.CAR_ID
            , C.CAR_TYPE
            , FLOOR (C.DAILY_FEE * (1 - (P.DISCOUNT_RATE / 100)) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        JOIN (
                SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE DURATION_TYPE = '30일 이상'
            ) P
        ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
        AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
              AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
        )
) SUB
WHERE SUB.FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;