-- 각 연/월마다 결제한 사용자 수를 성별로 집계하는 문제
-- EXTRACT 함수는 날짜나 타임스탬프에서 특정요소(연, 월, 일 등)을 숫자로 뽑아내는 함수
SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR
    , EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH
    , U.GENDER
    -- 한 사람이 여러 번 결제할 수 있기 때문에 중복 제거 필수
    , COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
    JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE)
    , EXTRACT(MONTH FROM O.SALES_DATE)
    , U.GENDER
ORDER BY YEAR, MONTH, GENDER
