-- 코드를 입력하세요
SELECT A.APNT_NO
    , P.PT_NAME
    , P.PT_NO
    , A.MCDP_CD
    , D.DR_NAME
    , A.APNT_YMD
FROM PATIENT P
    JOIN APPOINTMENT A
    ON P.PT_NO = A.PT_NO
    JOIN DOCTOR D
    ON D.DR_ID = A.MDDR_ID
    -- 시간을 TRUNC로 잘라서 해당 일자와 비교해야함
WHERE (TRUNC(A.APNT_YMD) = DATE '2022-04-13'
        AND A.APNT_CNCL_YN = 'N')
    AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD
