-- 계층쿼리를 통해 시간대 테이블 만들기
WITH HOURS AS (
    SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT H.HOUR
    , COUNT(A.DATETIME) AS COUNT
FROM HOURS H
    LEFT JOIN ANIMAL_OUTS A
    -- LPAD(문자열, 전체길이, 채울문자)
    ON TO_CHAR(A.DATETIME, 'HH24') = LPAD(H.HOUR, 2, '0')
GROUP BY H.HOUR
ORDER BY H.HOUR;