-- 코드를 입력하세요
WITH MAXCNT AS (
    SELECT COUNT(MEMBER_ID) AS CNT
        , MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) SUB
    )
)

SELECT P.MEMBER_NAME
    , R.REVIEW_TEXT
    -- 오라클에서는 TO_DATE가 아니라 TO_CHAR로 출력 형식을 변환해야 함
    , TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
    JOIN MAXCNT M
    ON P.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, R.REVIEW_TEXT