WITH T AS (
    SELECT
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS F,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS P,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'c#') AS C
    )

SELECT 
    CASE
        WHEN (D.SKILL_CODE & T.F) > 0
            AND (D.SKILL_CODE & T.P) > 0 THEN 'A'
        WHEN (D.SKILL_CODE & T.C) > 0 THEN 'B'
        WHEN (D.SKILL_CODE & T.F) >0 THEN 'C'
        ELSE NULL
    END AS GRADE
    , D.ID
    , D.EMAIL
FROM DEVELOPERS D
    JOIN T T
WHERE (D.SKILL_CODE & T.F) > 0
    OR (D.SKILL_CODE & T.C) > 0
ORDER BY GRADE, D.ID
